= PocketnetCore installation guide
:Author:    Andy Oknen
:Email:     core@pocketnet.app

== 1. Подготовка

Для запуска PocketnetCore ноды в контейнере Docker требуются некоторые знания работы с утилитами командрой строки:

* `shell`, `bash`, `zsh` или другие в Linux
* `PowerShell`, `cmd` или другие в Windows

Также вам могут потребоваться навыки работы с текстовыми редакторами `nano`, `vim`, `mcedit` или любых других.

Перед прочтением данного документа, убедитесь что ваш ПК соответствует заявленным требованиям:

* Windows or Linux (MacOs is not available yet)
* 4 core CPU
* 2GB free RAM
* 100GB free disk space
* SSD drive is recommended - do not use old HDD drives to avoid performance degradation
* 10Mbps internet connection

NOTE: В этом руководстве мы будем использовать ОС Linux


== 2. Install Docker
Установите сервер Docker для вашей ОС, согласно link:https://docs.docker.com/engine/install/[инструкциям].
Убедитесь, что в командной строке выполняется команда:

[source,shell]
----
$ docker --version
Docker version 20.10.11, build dea9396
----

NOTE: Версия может отличаться, мы рекомендуем использовать последнюю стабильную версию


== 3. Install Docker Compose
Установите Docker Compose согласно link:https://docs.docker.com/compose/install/[инструкциям].
Убедитесь, что в командной строке выполняется команда:

[source,shell]
----
$ docker-compose --version
docker-compose version 1.29.2, build 5becea4c
----

NOTE: Версия может отличаться, мы рекомендуем использовать последнюю стабильную версию


== 4. Подготовка окружения
=== 4.1. Создайте каталог для хранения базы данных блокчейна.
В этом руководстве мы будем использовать скрытый каталог `.pocketcoin` в домашнем каталоге текущего пользователя:
[source,shell]
----
$ mkdir ~/.pocketcoin
$ cd ~/.pocketcoin
----

=== 4.2.  Создайте файл конфигурации `pocketcoin.conf`
[source,python]
----
server=1

rpcallowip=127.0.0.1
#rpcuser=<LOGIN>
#rpcpassword=<PASSWORD>

rpcworkqueue=10
rpcthreads=2

rpcpublicworkqueue=300
rpcpublicthreads=10

rpcpostworkqueue=500
rpcpostthreads=10

port=37070
rpcport=37071
publicrpcport=38081
staticrpcport=38082
restrpcport=38083
wsport=8087

api=1
wsuse=1
rest=0

#debug=stat
#debug=consensus
#debug=sync
----

=== 4.3. Создайте файл конфигурации `docker-compose.yml`
Замените в файле путь к каталогу базы данных на свой путь. Укажите свои значения лимита оперативной памяти. 
[source,yml]
----
version: '3.7'
services:
  pocketnet.core:
    container_name: pocketnet.core
    # You can also use the latest stable release as part of minor updates
    # image: pocketnetteam/pocketnet.core:0.20
    image: pocketnetteam/pocketnet.core:latest

    # Измените каталог `~/.pocketcoin` на выбранный вами в шаге 4.1
    volumes:
      - ~/.pocketcoin:/home/pocketcore/.pocketcoin

    # Нода использует следующие порты для связи с другими нодами в сети,
    # а также для предоставления АПИ конечным пользователям
    ports:
      # To accept connections from other network nodes
      - 37070:37070
      # Manage node. Be careful - port 37071 opens access to your node and wallet
      # - 37071:37071
      # To accept HTTP POST requests along the path 127.0.0.1:38081/public/
      - 38081:38081
      # For the ability to establish a WebSocket connection to a node to support notifications
      - 8087:8087
    
    # Рекомендуется автоматический перезапуск ноды при сбоях
    restart: on-failure

    # Для корректной остановки ноды необходимо время на подготовку БД к закрытию
    stop_grace_period: 1m30s

    # Вы можете ограничить оперативную память контейнера
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 300M

    # Ограничить размер и количество лог файлов docker
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
----


== 5. Первичная синхронизация ноды
Помимо полной синхронизации ноды, которая может занять до нескольких дней, возможна инициализация базы данных путем загрузки и распаковки архива https://snapshot.pocketnet.app/latest.tgz

[source,shell]
----
$ curl -f https://snapshot.pocketnet.app/latest.tgz
$ tar -xzf latest.tgz -C ~/.pocketcoin
$ rm latest.tgz
----


== 6. Запуск ноды
Вы можете запустить контейнер командой `up` утилиты `docker-compose`. Добавьте параметр `-d` для запуска в фоновом режиме:
[source,shell]
----
$ docker-compose up -d pocketnet.core
----


== 7. Работа с нодой
Для доступа к интерфейсу ноды используется утилита `pocketcoin-cli`, входящая в состав образа docker. Для ее использования можно использовать команду `docker exec -t <container_name> <commands>`:
[source,shell]
$ docker exec -it pocketnet.core pocketcoin-cli help

Логи ноды расположены в каталоге базы данных в файле `debug.log`:
[source,shell]
$ tail 100 -f ~/.pocketcoind/debug.log

Также лог можно доступен через docker:
[source,shell]
$ docker logs --tail 100 -f pocketnet.core

