= Bastyon Barter App (Barteron)
:author: Andy Oknen <andy.oknen@ya.ru>

== Pocketnet Transaction v2

В новой системе консенсуса предполагается гибкое использование транзакций. Это означает, что поля пэйлоада могут заполнятся клиентом в произвольном формате, кроме некоторых полей, которые используются для консенсуса.

Поля верхнего уровня используются для реализации правил консенсуса и будут валидироваться на уровне узла. Поля второго уровня (объект `p`, `Payload`) могут заполняться в свободной форме для реализации функционала приложения.

Для реализации нештатной логики данные `Payload` могут быть использованы узлом для индексации дополнительных таблиц. Соглашения о структуре данных должны быть описаны и согласованы с кодом приложения.

Barteron транзакции имеют переходную форму перед Transaction v2 и начинают использовать механизмы нового консенсуса и индексирования дополнительных данных.

.Общая структура полей транзакции
[,json]
----
{
  "s1": <ADDRESS>, # Reserved
  "s2": <VARIANT>, # Reserved
  "s3": <VARIANT>, # Reserved
  "s4": <VARIANT>, # Reserved
  "s5": <VARIANT>, # Reserved
  "i1": <VARIANT>, # Reserved
  "p": {
    "s1": <CUSTOM>,
    "s2": <CUSTOM>,
    "s3": <CUSTOM>,
    "s4": <CUSTOM>,
    "s5": <CUSTOM>,
    "s6": <CUSTOM>,
    "s7": <CUSTOM>
  }
}
----


== Barteron Account

.OP_RETURN code
----
6272746163636f756e74
----

.Required payload elements:
[,json]
----
{
  "p": {
    "s4": {
      "t": { # Tags
        "a": [ <TAG>, <TAG>, ... ] # Append tags,
        "r": [ <TAG>, <TAG>, ... ] # Remove tags
      }
    }
  }
}
----


== Barteron Offer

.OP_RETURN code
----
6272746f66666572
----

.Required payload elements:
[,json]
----
{
  "p": {
    "s4": {
      "t": <TAG>
    }
  }
}
----
