= Bastyon Barter App (Barteron)
:author: Andy Oknen <andy.oknen@ya.ru>

== Pocketnet Transaction v2

В новой системе консенсуса предполагается гибкое использование транзакций. Это означает, что поля пэйлоада могут заполнятся клиентом в произвольном формате, кроме некоторых полей, которые используются для консенсуса.

Поля верхнего уровня используются для реализации правил консенсуса и будут валидироваться на уровне узла. Поля второго уровня (объект `p`, `Payload`) могут заполняться в свободной форме для реализации функционала приложения.

Для реализации нештатной логики данные `Payload` могут быть использованы узлом для индексации дополнительных таблиц. Соглашения о структуре данных должны быть описаны и согласованы с кодом приложения.

Barteron транзакции имеют переходную форму перед Transaction v2 и начинают использовать механизмы нового консенсуса и индексирования дополнительных данных.

.Общая структура полей транзакции
[,json]
----
{
  "s1": <ADDRESS>, # Reserved
  "s2": <VARIANT>, # Reserved
  "s3": <VARIANT>, # Reserved
  "s4": <VARIANT>, # Reserved
  "s5": <VARIANT>, # Reserved
  "i1": <VARIANT>, # Reserved
  "p": {
    "s1": <CUSTOM>,
    "s2": <CUSTOM>,
    "s3": <CUSTOM>,
    "s4": <CUSTOM>,
    "s5": <CUSTOM>,
    "s6": <CUSTOM>,
    "s7": <CUSTOM>
  }
}
----


== Barteron Account

.OP_RETURN code
----
6272746163636f756e74
----

.Required payload elements:
[,json]
----
{
  "p": {
    "s4": {
      // Allowed fixed account tags for barter
      "a": [
        <TAG>,
        <TAG>,
        ...
      ]
    }
  }
}
----


== Barteron Offer

.OP_RETURN code
----
6272746f66666572
----

.Required payload elements:
[,json]
----
{
  "p": {
    "s4": {
      // General offer tag
      "t": <TAG>,
      // Allowed offer tags for barter
      "a": [
        <TAG>,
        <TAG>,
        ...
      ]
    }
  }
}
----


== Barteron APIs

=== Get accounts transactions
[,json]
----
> /rpc/getbarteronaccounts [ <address1>, <address2>, ... ]
{
  "result": "success",
    "data": [
      {
        "hash": "d574b6389d91c42b37cd8bc5ec257ceb803986ad38ebb83cf7fdabee34fe9af7",
        "type": 104,
        "height": 1063,
        "blockHash": "031e4da9305a5d9e8269155a9ad2586c4945bf560c89c2ee584663687a0fad4f",
        "time": 1690098322,
        "s1": "muA1gPR5JjsxZbeCj7HB2wrx4h3Ky8iHY3",
        "p": {
            "s4": "{\"a\": [1, 2, 3, 4, 5]}"
        }
      }
  ]
}
----

=== Get offers information
[,json]
----
> /rpc/getbarteronoffers [ <txhash1>, <txhash2>, ... ]
{
  "result": "success",
    "data": {
      ...
    }
}
----

=== Get offers feed
[,json]
----
> /rpc/getbarteronoffersfeed <?filter> <topHeight> <pageStart> <pageSize> <orderBy> <desc>
{
  "result": "success",
    "data": [
      { offer_instance },
      { offer_instance },
      ...
    ]
}
----

=== Get potencial offer deals
[,json]
----
> /rpc/getbarterondeals <txhash of offer>
{
  "result": "success",
    "data": [
      { offer_instance ? },
      { offer_instance ? },
      ...
    ]
}
----