= Bastyon Moderation System
:author: Andy Oknen <andy.oknen@ya.ru>

== Flags

Жалобы позволяют пользователям отмечать контент нежелательным (пост или комментарий и автора).
Для разграничения жалоб применяется числовое значения `REASON`:

1. 111
2. 222
3. 333
4. 444
5. 555


=== Условия создания жюри

Любой флаг может инициировать создание "жюри". Если жюри инициировано, все последующие флаги игнорируются. Для создания жюри учитываются следующие правила:

- Рассматриваемый аккаунт не находится в активном бане
- Кол-во флагов с таким же `REASON`, `CONTENT_TX_HASH` и `ADDRESS_HASH` должно быть `>= [main:20, test:5, reg:2]`
- Глубина поиска схожих флагов `FLAG_HEIGHT > (CURRENT_HEIGHT - [main:43200, test:4320, reg:10])`


=== Транзакция

.OP_RETURN code
----
6d6f64466c6167
----

.Payload structure
[,json]
----
{
    "s2": "<CONTENT_TX_HASH>",
    "s3": "<ADDRESS_HASH>",
    "i1": "<REASON>"
}
----


== Jury

Жюри не является транзакцией, представляет из себя запись в БД и содержит следующие поля:

- Ссылка на Флаг, инициирующий создание жюри.
- Ссылка на аккаунт, автора контента.
- Числовой код причины жалобы.

Совместно с записью жюри происходит выбор модераторов:

- Для фильтрации списка модераторов используется хэш транзакции флага `FLAG_HASH`, инициировавшего создание жюри.
- В качестве сортировки модераторов используется хэш транзакции регистрации аккаунта модератора `ACCOUNT_HASH`.
- Для решения вопроса жюри отбираются ТM аккаунтов `[main:80, test:6 reg:4]`
- Для равномерного распределения модераторов аккаунты отбираются по следующим условиям:
  * Отбирается TM/2 аккаунтов где `ACCOUNT_HASH < FLAG_HASH`
  * Отбирается TM/2 аккаунтов где `ACCOUNT_HASH > FLAG_HASH`


== Vote

Голос модератора, имеющий два значения `0|1`, означающие, согласен модератор с жалобами или нет. Любой голос может иницировать вердикт жюри.

- Вердикт положительный, если голос удовлетворяет условию, что он является N'м по счету положительным голосом `[main:8, test:3, reg:2]`.
- Отрицательный вердикт выносится вместе с первым отрицательным голосом любого модератора.
- После вынесения вердикта (положительного или отрицательного) все голоса игнорируются.
- Жюри без вердикта является бессрочным.

=== Транзакция

.OP_RETURN code
----
6d6f64566f7465
----

.Payload structure
[,json]
----
{
    "s2": "<JURY_ID>",
    "i1": "<VERDICT>"
}
----

`JURY_ID` - хэш транзакции флага, инициировавшей жюри

`VERDICT` - числовое значение `0|1`


== Ban Account

Бан аккаунта, также как и жюри, не является транзакцией. Представляет из себя запись в БД и содержит следующие поля:

- Ссылка на голос, инициирующий блокировку.
- Ссылка на аккаунт, автора контента.
- Высота окончания блокировки. Срок блокировки определяется исходя из правил:
  * Первая блокировка - `[main:43200, test:5000, reg:100]` блоков
  * Вторая блокировка - `[main:129600, test:10000, reg:200]` блоков
  * Третья блокировка - `[main:51840000, test:15000, reg:1000]` блоков

Аккаунт, заблокированный нодой, не имеет права создавать Social транзакции, но может создавать денежные транзакции без ограничений.

Другие аккаунты имеют право совершать действия с заблокированным аккаунтом (ставить оценки, комментарии и т.д.).



== Правила скрытия контента и аккаунтов

Аккаунты, находящиеся в активном жюри, бане или имеющих N активных жалоб должны скрываться из ленты и поиска.

TODO